---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Install packages
    yum:
      name:
      - lvm2
      use_backend: dnf
    ignore_errors: yes      
  - name: Format disks for worker nodes
    script: ./format_disks.sh nvme1n1
    when: node_pool == "worker"
  - name: Enable and start iscsi daemon
    service:
      name: iscsid
      state: started
      enabled: yes
    ignore_errors: yes

