---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Copy containerd config
    template:
      src: config.toml.tmpl
      dest: /etc/containerd/config.toml
      owner: root
      group: root
  - name: Restart containerd
    service:
      name: containerd
      state: restarted
